# Generated by Django 4.2 on 2023-05-17 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baham', '0003_vehiclemodel_created_by_vehiclemodel_date_voided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
