# Generated by Django 4.2 on 2023-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baham', '0004_vehiclemodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='date_voided',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='is_voided',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='void_reason',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='voided_by',
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
